app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    path: /
    defaults: { _controller: AppBundle:Default:index}

home:
    path: /home
    defaults: { _controller: AppBundle:Default:index}

werdegang:
    path: /werdegang
    defaults: { _controller: AppBundle:Default:index}

kenntnisse:
    path: /kenntnisse
    defaults: { _controller: AppBundle:Default:index}

motivation:
    path: /motivation
    defaults: { _controller: AppBundle:Default:index}

projects:
    path: /projekte
    defaults: { _controller: AppBundle:Default:index}

impressum:
    path: /impressum
    defaults: { _controller: AppBundle:Default:index}